---
title: "hs_extract_pts"
author: "Tao Huang"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

https://cu-esiil.github.io/data-library/remote_sensing/neon_hyperspectral/neon_hyperspectral/

The goal of neonhs is to make data from the National Ecological Observatory Network (NEON) Airborne Observation Platform (AOP) hyperspectral instrument easier to use. 

```{r}
#install.packages('devtools')
#devtools::install_github('earthlab/neonhs')

library(neonhs)
library(raster)
#install.packages("viridis")
library(viridis)
library(sp)
library(tidyverse)

path_to_file <- system.file('extdata', 'ex.h5', package = 'neonhs')
r <- hs_read(path_to_file, bands = c(1, 50, 100, 400))
r

plot(r, col = cividis(100), axes = FALSE, box = FALSE)

```

```{r}
pts <- SpatialPointsDataFrame(coords = data.frame(x = c(257025, 257011),
                                                  y = c(4111982, 4111991)), 
                              data = data.frame(id = 1:2),
                              proj4string = CRS(hs_proj4string(path_to_file)))
plot(r[[1]], axes = FALSE, box = FALSE)
plot(pts, add = TRUE)

```

```{r}
vals <- hs_extract_pts(path_to_file, pts = pts, bands = 1:426)
vals


vals %>%
  as_tibble() %>%
  dplyr::select(id, starts_with('band')) %>%
  gather(band, reflectance, -id) %>%
  separate(band, c('index', 'wavelength')) %>%
  mutate(wavelength = parse_number(wavelength)) %>%
  ggplot(aes(wavelength, reflectance, group = id)) + 
  geom_line() + 
  xlab('Wavelength (nm)') + 
  ylab('Reflectance')

```
